# -*- coding: utf-8 -*-
"""mlpredicition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TzryVlQd9zKl5ND-ScycmlEKNCtrnoGj
"""

# =========================================
# INSTALL REQUIRED LIBRARIES
# =========================================
!pip install xgboost folium geopandas shapely --quiet

# =========================================
# IMPORT LIBRARIES
# =========================================
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score
import folium
from folium.plugins import HeatMap
from IPython.display import display, HTML

# =========================================
# LOAD DATA
# =========================================
df = pd.read_csv('preprocessed_hourly_data.csv')

# =========================================
# TIME FEATURE ENGINEERING
# =========================================
df['time'] = pd.to_datetime(df['time'])
df['hour'] = df['time'].dt.hour
df['day'] = df['time'].dt.day
df['month'] = df['time'].dt.month
df['dayofweek'] = df['time'].dt.dayofweek
df = df.drop(columns=['time'])

# =========================================
# DEFINE FEATURES & TARGETS
# =========================================
features = ['latitude','longitude','u10','v10','t2m','sst','tp',
            'hour','day','month','dayofweek']
targets = ['pm2p5','pm10','co','no2','go3','so2']

X = df[features]
y = df[targets]

# =========================================
# TRAIN TEST SPLIT
# =========================================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

# =========================================
# TRAIN XGBOOST MODEL
# =========================================
xgb = XGBRegressor(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    objective='reg:squarederror'
)
model = MultiOutputRegressor(xgb)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Model R2 Score:", r2_score(y_test, y_pred))

# =========================================
# AQI SUBINDEX FUNCTION + BREAKPOINTS
# =========================================
def subindex(conc, breakpoints):
    for Clow, Chigh, Ilow, Ihigh in breakpoints:
        if conc <= Chigh:
            return ((Ihigh - Ilow)/(Chigh - Clow)) * (conc - Clow) + Ilow
    return 500

pm25_bp = [(0,30,0,50),(30,60,50,100),(60,90,100,200),
           (90,120,200,300),(120,250,300,400),(250,500,400,500)]
pm10_bp = [(0,50,0,50),(50,100,50,100),(100,250,100,200),
           (250,350,200,300),(350,430,300,400),(430,600,400,500)]
no2_bp  = [(0,40,0,50),(40,80,50,100),(80,180,100,200),
           (180,280,200,300),(280,400,300,400),(400,800,400,500)]
o3_bp   = [(0,50,0,50),(50,100,50,100),(100,168,100,200),
           (168,208,200,300),(208,748,300,400),(748,1000,400,500)]
co_bp   = [(0,1,0,50),(1,2,50,100),(2,10,100,200),
           (10,17,200,300),(17,34,300,400),(34,50,400,500)]
so2_bp  = [(0,40,0,50),(40,80,50,100),(80,380,100,200),
           (380,800,200,300),(800,1600,300,400),(1600,2000,400,500)]

def compute_aqi(df_in):
    d = df_in.copy().clip(lower=0)
    d['AQI_PM25'] = d['pm2p5'].apply(lambda x: subindex(x, pm25_bp))
    d['AQI_PM10'] = d['pm10'].apply(lambda x: subindex(x, pm10_bp))
    d['AQI_NO2']  = d['no2'].apply(lambda x: subindex(x, no2_bp))
    d['AQI_O3']   = d['go3'].apply(lambda x: subindex(x, o3_bp))
    d['AQI_CO']   = d['co'].apply(lambda x: subindex(x, co_bp))
    d['AQI_SO2']  = d['so2'].apply(lambda x: subindex(x, so2_bp))
    d['Final_AQI'] = d[['AQI_PM25','AQI_PM10','AQI_NO2',
                         'AQI_O3','AQI_CO','AQI_SO2']].max(axis=1)
    return d['Final_AQI']

# =========================================
# BUILD ACTUAL vs PREDICTED DATAFRAMES
# NO FILTERING NEEDED — dataset is already
# Kerala ERA5 grid points
# =========================================
actual_df = y_test.reset_index(drop=True).copy()
actual_df['latitude']  = X_test['latitude'].values
actual_df['longitude'] = X_test['longitude'].values
actual_df['Final_AQI'] = compute_aqi(actual_df)

pred_df = pd.DataFrame(y_pred, columns=targets)
pred_df['latitude']  = X_test['latitude'].values
pred_df['longitude'] = X_test['longitude'].values
pred_df['Final_AQI'] = compute_aqi(pred_df)

print("Actual AQI   — min:", round(actual_df['Final_AQI'].min(), 2),
      " max:", round(actual_df['Final_AQI'].max(), 2))
print("Predicted AQI — min:", round(pred_df['Final_AQI'].min(), 2),
      " max:", round(pred_df['Final_AQI'].max(), 2))
print("Test points:", len(actual_df))

# =========================================
# SHARED NORMALISATION (same scale = fair comparison)
# =========================================
global_min = min(actual_df['Final_AQI'].min(), pred_df['Final_AQI'].min())
global_max = max(actual_df['Final_AQI'].max(), pred_df['Final_AQI'].max())

def normalise(series):
    return (series - global_min) / (global_max - global_min)

actual_df['AQI_norm'] = normalise(actual_df['Final_AQI'])
pred_df['AQI_norm']   = normalise(pred_df['Final_AQI'])

# =========================================
# LOAD KERALA BOUNDARY (for visual outline only)
# =========================================
states = gpd.read_file(
    "https://geodata.ucdavis.edu/gadm/gadm4.1/json/gadm41_IND_1.json"
)
kerala = states[states['NAME_1'] == 'Kerala'].to_crs("EPSG:4326")

# =========================================
# HELPER: BUILD HEATMAP
# =========================================
# =========================================
# HELPER: BUILD HEATMAP WITH KERALA MASK
# =========================================
def build_heatmap(df_map, title):
    m = folium.Map(location=[10.5, 76.0], zoom_start=7)

    # Add heatmap with large radius to fill Kerala
    heat_data = [
        [row['latitude'], row['longitude'], row['AQI_norm']]
        for _, row in df_map.iterrows()
    ]
    HeatMap(
        heat_data,
        radius=60,    # large enough to fill gaps between sparse ERA5 points
        blur=50,      # smooth blending across the state
        min_opacity=0.4,
        max_zoom=10
    ).add_to(m)

    # Mask everything OUTSIDE Kerala with white
    from shapely.geometry import mapping, box
    from shapely.ops import unary_union

    world = box(-180, -90, 180, 90)
    kerala_shape = unary_union(kerala.geometry.values)
    outside = world.difference(kerala_shape)

    folium.GeoJson(
        {"type": "Feature", "geometry": mapping(outside), "properties": {}},
        style_function=lambda x: {
            'fillColor': 'white',
            'fillOpacity': 1.0,
            'color': 'none',
            'weight': 0
        }
    ).add_to(m)

    # Kerala border on top
    folium.GeoJson(
        kerala,
        style_function=lambda x: {
            'fillColor': 'none',
            'color': 'blue',
            'weight': 2
        }
    ).add_to(m)

    title_html = f"""
    <div style="position:fixed; top:10px; left:50%; transform:translateX(-50%);
                background:white; padding:8px 16px; border-radius:6px;
                font-size:15px; font-weight:bold; z-index:9999;
                box-shadow:2px 2px 6px rgba(0,0,0,0.3);">
        {title}
    </div>"""
    m.get_root().html.add_child(folium.Element(title_html))
    return m
# =========================================
# BUILD & SAVE BOTH MAPS
# =========================================
map_actual = build_heatmap(actual_df, "✅ Actual AQI — Test Set (Ground Truth)")
map_actual.save("heatmap_actual.html")
print("Saved: heatmap_actual.html")

map_pred = build_heatmap(pred_df, "🤖 Predicted AQI — Test Set (Model Output)")
map_pred.save("heatmap_predicted.html")
print("Saved: heatmap_predicted.html")

# =========================================
# DISPLAY BOTH MAPS SIDE BY SIDE
# =========================================
actual_html = open("heatmap_actual.html").read()
pred_html   = open("heatmap_predicted.html").read()

combined = f"""
<div style="display:flex; gap:10px;">
    <div style="flex:1;">
        <h3 style="text-align:center; font-family:sans-serif;">✅ Actual AQI (Ground Truth)</h3>
        <iframe srcdoc='{actual_html.replace("'", "&apos;")}'
                width="100%" height="520px" frameborder="0"></iframe>
    </div>
    <div style="flex:1;">
        <h3 style="text-align:center; font-family:sans-serif;">🤖 Predicted AQI (Model Output)</h3>
        <iframe srcdoc='{pred_html.replace("'", "&apos;")}'
                width="100%" height="520px" frameborder="0"></iframe>
    </div>
</div>
"""
display(HTML(combined))

jupyter nbconvert --to script

